appId: ir.tgbs.peccharge
flows:
  - test.yaml
env:
  LOGIN_MOBILE: "09124168652"
  TEST_OTP: "123456"
  TEST_MOBILE: "09029868952"
  SOURCE_CARD: "6221061237612546"
  DESTINATION_CARD: "5022291062874795"
  SOURCE_CARD_EXP_MONTH: "02"
  SOURCE_CARD_EXP_YEAR: "02"
  TEST_CARD_NAME: "sami"
  TEST_BILL_NAME: "test"
  ELECTRICITY_BILL_ID: "9429190504123"
  GAS_BILL_ID: "9157197136"
  WATER_BILL_ID: "1561377299219"
  PHONE_BILL_NUMBER: "02144146339"
  OTHER_BILL_ID: "1561377299219"
  OTHER_PAYMENT_ID: "5555454545"
  VEHICLE_FINE_BILL_ID: "1561377299219"
  VEHICLE_FINE_PAYMENT_ID: "5555454545"
  INVALID_LOW_AMOUNT: "2"
  INVALID_HIGH_AMOUNT: "2000000000000"
  TRANSFER_AMOUNT: "2000000"
  TRANSFER_DESCRIPTION: "2000000 hjk khj kjh jhkj khjh kjh kjh jkh jh kh hjkh jh jhjhjhyg yyu y yyg jjhg hjgjhg hgy ygyug yugyg ug"
  INVALID_LOW_CHARGE_AMOUNT: "100"
  INVALID_HIGH_CHARGE_AMOUNT: "2000000"
  CHARGE_AMOUNT: "199990"
  INVALID_EXTREME_CHARGE_AMOUNT: "9999999999"
  # Replace these with the exact success messages displayed by your app.
  CHARGE_SUCCESS_TEXT: "عملیات با موفقیت انجام شد"
  TRANSFER_SUCCESS_TEXT: "عملیات با موفقیت انجام شد"
