appId: ir.tgbs.peccharge.web
---

- tapOn:
    id: "left_button"
    index: 1
- assertVisible:
    id: "mobileNumber"

- tapOn:
    id: "mobileNumber"
- eraseText 
- eraseText: 100

- tapOn: "تایید و ادامه"
- assertVisible:
    id: "creditSimButton"

- tapOn: 
    id: "creditSimButton"
- assertVisible:
    id: "container"

- tapOn:
    id: "mobileNumber"
- inputText: "09029868952"


- assertVisible:
    id: "estelamButton"

- tapOn: "تایید و ادامه"
- back


- tapOn:
    id: "contactsButton"


- tapOn:
    id: "main"

- assertVisible: "Select Contact"
- runFlow:
    when:
      visible: "Just once"
      
    commands:
        - tapOn: "Just once"
       


- runFlow:
    when:
      notVisible: "Just once"
      
    commands:
        - tapOn: ".*Sa.*"
       



- tapOn: "تایید و ادامه"
#- tapOn: 
 #   id: "creditSimButton"

- runFlow:
    when:
      visible: 
        id : "creditSimButton"
     # visible:  "تایید و ادامه"
    file: packagetwo.yaml

#- tapOn: "تایید و ادامه"
#- tapOn:
   # id: "homeSimButton"


