appId: ${APP_ID}
---

- tapOn:
    id: "left_button"
    index: 1
- assertVisible:
    id: "mobileNumber"

- tapOn:
    id: "mobileNumber"
- eraseText 
- eraseText: 100
- tapOn:
    id: "mobileNumber"
- inputText: ""
- eraseText 
- tapOn: "تایید و ادامه"
- assertVisible:
    id: "creditSimButton"

- tapOn: 
    id: "creditSimButton"
- assertVisible:
    id: "container"

- tapOn:
    id: "mobileNumber"
- inputText: ""
- eraseText 
- tapOn:
    id: "mobileNumber"
- inputText: ${TEST_MOBILE}


- assertVisible:
    id: "estelamButton"

- tapOn: "تایید و ادامه"
- back


#- tapOn:
 #   id: "contactsButton"


#- tapOn:
 #   id: "main"

- runFlow:
    when:
      visible: "Just once"
      
    commands:
        - tapOn: "Just once"
       


#- runFlow:
 #   when:
  #    notVisible: "Just once"
      
   # commands:
    #    - tapOn: ".*Sa.*"
       



#- tapOn: "تایید و ادامه"
#- tapOn: 
 #   id: "creditSimButton"
#- back
- tapOn: "تایید و ادامه"
- assertVisible:
    id: "creditSimButton"
- runFlow: packagetwo.yaml

#- tapOn: "تایید و ادامه"
#- tapOn:
   # id: "homeSimButton"


